openapi: 3.0.0
info:
  title: Dataset Control Validation API
  version: 1.0.0
  description: Internal API contracts for polyline validation against shapefiles

paths:
  /validate_row:
    post:
      summary: Validate a single observation row
      operationId: validateRow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'

  /generate_report:
    post:
      summary: Generate per-link validation report
      operationId: generateReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRequest'
      responses:
        '200':
          description: Link report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResult'

components:
  schemas:
    ValidationRequest:
      type: object
      required:
        - row_data
        - shapefile_path
        - parameters
      properties:
        row_data:
          type: object
          properties:
            data_id:
              type: string
            name:
              type: string
            route_alternative:
              type: integer
            timestamp:
              type: string
              format: date-time
            polyline:
              type: string
        shapefile_path:
          type: string
        parameters:
          $ref: '#/components/schemas/ValidationParameters'

    ValidationResult:
      type: object
      properties:
        is_valid:
          type: boolean
        valid_code:
          type: integer
          minimum: 0
          maximum: 93
        diagnostics:
          type: object
          properties:
            hausdorff_distance:
              type: number
              nullable: true
            length_ratio:
              type: number
              nullable: true
            coverage:
              type: number
              nullable: true
            matched_alternative:
              type: integer
              nullable: true

    ValidationParameters:
      type: object
      properties:
        hausdorff_threshold_m:
          type: number
          default: 5.0
        length_check_mode:
          type: string
          enum: ["off", "ratio", "exact"]
          default: "ratio"
        length_ratio_min:
          type: number
          default: 0.90
        length_ratio_max:
          type: number
          default: 1.10
        epsilon_length_m:
          type: number
          default: 0.5
        coverage_min:
          type: number
          default: 0.85
        coverage_spacing_m:
          type: number
          default: 1.0
        min_link_length_m:
          type: number
          default: 20.0
        crs_metric:
          type: string
          default: "EPSG:2039"
        polyline_precision:
          type: integer
          default: 5

    ReportRequest:
      type: object
      required:
        - validated_data_path
        - shapefile_path
      properties:
        validated_data_path:
          type: string
        shapefile_path:
          type: string
        date_filter:
          type: object
          properties:
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
            specific_day:
              type: string
              format: date

    ReportResult:
      type: object
      properties:
        output_shapefile_path:
          type: string
        summary:
          type: object
          properties:
            total_links:
              type: integer
            links_with_data:
              type: integer
            links_all_valid:
              type: integer
            links_partial_valid:
              type: integer
            links_all_invalid:
              type: integer
            links_not_recorded:
              type: integer